apiVersion: v1
kind: ServiceAccount
metadata:
  name: hospital
  namespace: hospital-system
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: hospital
rules:
  - apiGroups: [""]
    resources: ["pods"]
    verbs: ["get", "list", "delete"]
  - apiGroups: [""]
    resources: ["nodes"]
    verbs: ["get", "update", "patch"]
  - apiGroups: ["apps"]
    resources: ["deployments", "statefulsets"]
    verbs: ["get", "list", "update", "patch"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: hospital
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: hospital
subjects:
  - kind: ServiceAccount
    name: hospital
    namespace: hospital-system
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: surgeon
  namespace: hospital-system
